import type { Metadata } from 'next'
import './globals.css'
import MainLayout from './components/MainLayout'

import { Ubuntu } from 'next/font/google'

const ubuntu = Ubuntu({
  weight: '400',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} bg-shade_9`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
